---
name: hello
version: 1.0.0.0

license: MIT
license-file: LICENSE

dependencies:
  - base
  - bytestring
  - optparse-applicative
  - optparse-generic
  - relude
  - text
  - genvalidity
  - genvalidity-text
  - sydtest

library:
  source-dirs: ./src/

ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

executables:
  hello:
    main: Main.hs
    source-dirs: ./src/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  hello-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - genvalidity-sydtest
      - sydtest
      - sydtest-discover
      - hello
