name: build
on: push
jobs:
  nix-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --accept-flake-config

  haskell-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@master
        with:
          name: opensource
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: damianfral/nix-cache-lookup@master
        id: cache-lookup-hello
        with:
          flake-attribute: ".?dir=haskell-cli#hello"
      - run: nix build -L ".?dir=haskell-cli#hello" --accept-flake-config
        if: steps.cache-lookup-hello.outputs.cached != 'true'
      - uses: damianfral/nix-cache-lookup@master
        id: cache-lookup-dev-shell-default
        with:
          flake-attribute: ".?dir=haskell-cli#devShells.x86_64-linux.default"
      - run: nix build -L ".?dir=haskell-cli#devShells.x86_64-linux.default" --accept-flake-config
        if: steps.cache-lookup-dev-shell-default.outputs.cached != 'true'
      - run: nix flake check ".?dir=haskell-cli" --accept-flake-config
